In [13]:
import pandas as pd
import json
from pathlib import Path

In [14]:
folder = "C:/Users/Laura GF/Documents/GitHub/machine-learning-capstone/data/"
raw_data = f'{folder}raw-data/'
clean_data = f'{folder}clean-data/'

In [15]:
json_2021_df = pd.read_json(Path(raw_data,"2021_canada_vehicle_sales.json"))

In [16]:
json_2021_df.dropna(how="all", inplace=True)

In [17]:
json_2021_df.sort_values(by='model')

,model,jan,feb,mar,apr,may,jun,jul,aug,sep,oct,nov,dec
0,Acura ILX,62,65,124,116,93,73,70,68,58,59,39,43
1,Acura MDX,93,389,782,611,550,501,347,516,309,406,303,275
2,Acura NSX,0,2,3,5,5,1,1,2,3,0,1,0
3,Acura RDX,443,466,650,552,607,738,747,720,788,854,661,750
4,Acura RLX,0,0,1,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
293,Volvo 60-Series,98,98,110,0,134,81,121,157,95,122,158,96
294,Volvo 90-Series,7,7,8,15,19,12,15,19,12,23,29,18
295,Volvo XC40,222,222,250,369,477,289,252,327,198,224,290,176
296,Volvo XC60,155,155,174,241,312,189,395,511,309,311,402,244
297,Volvo XC90,190,190,214,261,338,205,281,364,220,192,249,151

In [ ]:
Volvo XC60	155	155	174	241	312	189	395	511	309	311	402	244